name: Meddela Discord
on:
 pull_request:
   branches: [ main ]
jobs:
 run-kontroll-check:
  uses: ./.github/workflows/kontroll.yml


 notis:
  needs: run-kontroll-check
  runs-on: ubuntu-latest
  if: always()
  steps:
   - uses: actions/checkout@v4
     with:
       ref: ${{ github.event.pull_request.head.sha }}
   - name: hämta commit-meddelande
     id: commit
     run: echo "message=$(git log -1 --pretty=%s)" >> "$GITHUB_OUTPUT"

   - name: Skicka meddelande om lyckad kontroll
     if: needs.run-kontroll-check.result == 'success'
     env:
       WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
       VEM: ${{ github.actor }}
       REPO: ${{ github.repository }}
       PullRequest: ${{ github.event.pull_request.title }}
       CommitMsg: ${{ steps.commit.outputs.message }}

     run: |
       curl -X POST -H "Content-Type: application/json" \
         -d "{\"content\": \"$VEM skapade en pull request i $REPO med commit-meddelande $CommitMsg: $PullRequest\"}" \
         "$WEBHOOK"
    
   - name: Skicka meddelande om misslyckad kontroll
     if: needs.run-kontroll-check.result == 'failure'
     env:
       WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
       VEM: ${{ github.actor }}
       REPO: ${{ github.repository }}
       PullRequest: ${{ github.event.pull_request.title }}
       CommitMsg: ${{ steps.commit.outputs.message }}
     run: |
       curl -X POST -H "Content-Type: application/json" \
         -d "{\"content\": \"$VEM skapade en pull request med misslyckad kontroll i $REPO med commit-meddelande $CommitMsg: $PullRequest\"}" \
         "$WEBHOOK"